/*
 * This source file was generated by the Gradle 'init' task
 */
package exception_concept;

import java.io.IOException;

public class App {
  public String getGreeting() {
    return "Hello World!";
  }

  public static void main(String[] args) {
    System.out.println(new App().getGreeting());
    CheckedExceptions chkExp = new CheckedExceptions();
    UnCheckedExceptions unChkExp = new UnCheckedExceptions();
    Errors err = new Errors();
    ThrowHandling th = new ThrowHandling();

    // chkExp
    // chkExp.eFileNotFoundException();
    
    chkExp.noSearchException("none1.exe");

    try {
      chkExp.noSearchException2("none1.exe");
    } catch (IOException e) {
      e.printStackTrace();
    }

    // unChkExp
    // try {
    //   unChkExp.eArrayIndexOutOfBoundsException();
    // } catch (ArrayIndexOutOfBoundsException ae) {
    //   System.out.println("main catch");
    //   ae.printStackTrace();
    // }
    // unChkExp.eArrayIndexOutOfBoundsException();

    // err
    // err.eOutOfMemoryError();

    // th
    // th.throwsHandlFileNotFoundException();
    // try {
    //   th.throwHandlClassCastException();
    // } catch (ClassCastException ce) {
    //   System.out.println("main catch");
    //   ce.printStackTrace();
    // }

  }

}
